In [5]:
import pandas as pd

## Read Player Data

In [6]:
player_data = pd.read_csv("player_data_202502101344.csv")
club_data = pd.read_csv('club_ks_att_go_df_dis_atm_gl_dsc_202502060055.csv')

In [13]:
player_data.head()

,player_name,club,position,minutes_played,match_played,goals,assists,distance_covered,corner_taken,offsides,...,headers,penalties,others,inside_area,outside_areas,saved,saved_penalties,conceded,cleansheets,punches made
0,Courtois,Real Madrid,Goalkeeper,1230,13,0,0,64.2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,61.0,1.0,14.0,5.0,4.0
1,Vinícius Júnior,Real Madrid,Forward,1199,13,4,6,133.0,3.0,4.0,...,0.0,0.0,0.0,4.0,0.0,NaN,NaN,NaN,NaN,NaN
2,Benzema,Real Madrid,Forward,1106,12,15,1,121.5,2.0,9.0,...,3.0,3.0,0.0,13.0,2.0,NaN,NaN,NaN,NaN,NaN
3,Modrić,Real Madrid,Midfielder,1077,13,0,4,124.5,10.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Éder Militão,Real Madrid,Defender,1076,12,0,0,110.4,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
player_data.describe()

,minutes_played,match_played,goals,assists,distance_covered,corner_taken,offsides,dribbles,tackles,t_won,...,headers,penalties,others,inside_area,outside_areas,saved,saved_penalties,conceded,cleansheets,punches made
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,328.000000,328.000000,328.000000,887.000000,887.000000,...,319.000000,319.000000,319.000000,319.000000,319.000000,134.000000,134.000000,134.000000,134.000000,134.000000
mean,342.827000,5.203000,0.429000,0.364000,39.560500,2.158537,0.762195,6.341463,5.310034,2.197294,...,0.188088,0.112853,0.012539,1.297806,0.344828,7.276119,0.044776,3.089552,1.164179,0.895522
std,238.900239,2.640599,1.167185,0.822302,27.217944,5.028286,1.789753,8.747521,4.816701,2.444525,...,0.491163,0.426840,0.111449,1.641357,0.532199,8.608784,0.207588,4.750089,1.164603,1.928296
min,1.000000,1.000000,0.000000,0.000000,0.200000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,142.000000,3.000000,0.000000,0.000000,16.675000,0.000000,0.000000,2.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,1.000000,0.000000
50%,326.000000,5.000000,0.000000,0.000000,36.850000,0.000000,0.000000,3.000000,4.000000,1.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,3.000000,0.000000,0.000000,1.000000,0.000000
75%,500.000000,7.000000,0.000000,0.000000,58.550000,1.000000,1.000000,7.000000,9.000000,3.000000,...,0.000000,0.000000,0.000000,2.000000,1.000000,9.000000,0.000000,6.000000,1.000000,1.000000
max,1230.000000,13.000000,15.000000,7.000000,133.000000,36.000000,10.000000,83.000000,35.000000,18.000000,...,3.000000,3.000000,1.000000,13.000000,3.000000,61.000000,1.000000,20.000000,5.000000,12.000000

## Clean Data

In [22]:
duplicates = player_data[player_data.duplicated(subset=["player_name",'club'],keep=False)]
duplicates.describe()

,minutes_played,match_played,goals,assists,distance_covered,corner_taken,offsides,dribbles,tackles,t_won,...,headers,penalties,others,inside_area,outside_areas,saved,saved_penalties,conceded,cleansheets,punches made
count,284.000000,284.000000,284.000000,284.000000,284.000000,156.000000,156.0,156.000000,284.000000,284.000000,...,140.0,140.0,140.0,140.000000,140.000000,84.000000,84.0,84.000000,84.000000,84.000000
mean,369.169014,5.471831,0.239437,0.323944,42.738732,0.820513,0.0,3.333333,6.549296,2.478873,...,0.0,0.0,0.0,0.628571,0.514286,3.238095,0.0,0.523810,1.095238,0.142857
std,209.690432,2.415187,0.503410,0.757057,24.609719,2.434926,0.0,1.793657,4.016886,1.981249,...,0.0,0.0,0.0,0.723131,0.501590,1.313682,0.0,1.571402,0.926440,0.469372
min,18.000000,1.000000,0.000000,0.000000,3.300000,0.000000,0.0,1.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.000000,0.000000,2.000000,0.0,0.000000,0.000000,0.000000
25%,180.000000,4.000000,0.000000,0.000000,21.600000,0.000000,0.0,3.000000,3.000000,1.000000,...,0.0,0.0,0.0,0.000000,0.000000,3.000000,0.0,0.000000,1.000000,0.000000
50%,347.000000,5.500000,0.000000,0.000000,39.300000,0.000000,0.0,3.000000,7.000000,2.000000,...,0.0,0.0,0.0,0.000000,1.000000,3.000000,0.0,0.000000,1.000000,0.000000
75%,540.000000,8.000000,0.000000,0.000000,66.600000,0.000000,0.0,4.000000,10.000000,4.000000,...,0.0,0.0,0.0,1.000000,1.000000,3.000000,0.0,0.000000,1.000000,0.000000
max,867.000000,10.000000,2.000000,4.000000,96.300000,8.000000,0.0,8.000000,14.000000,7.000000,...,0.0,0.0,0.0,2.000000,1.000000,9.000000,0.0,7.000000,5.000000,2.000000

In [20]:
clean_player_data = player_data.drop_duplicates(subset=['player_name', 'club'], keep='first')

In [23]:
clean_player_data.describe()

,minutes_played,match_played,goals,assists,distance_covered,corner_taken,offsides,dribbles,tackles,t_won,...,headers,penalties,others,inside_area,outside_areas,saved,saved_penalties,conceded,cleansheets,punches made
count,745.000000,745.000000,745.000000,745.000000,745.000000,183.000000,183.000000,183.000000,632.000000,632.000000,...,190.000000,190.000000,190.000000,190.000000,190.000000,59.000000,59.000000,59.000000,59.000000,59.000000
mean,332.491275,5.100671,0.493960,0.377181,38.268456,3.256831,1.366120,8.792350,4.729430,2.087025,...,0.315789,0.189474,0.021053,1.778947,0.215789,12.542373,0.101695,6.644068,1.305085,1.932203
std,248.123209,2.716796,1.314836,0.846412,27.988625,6.183516,2.219383,11.024476,4.982812,2.602636,...,0.604448,0.540326,0.143939,1.903375,0.515129,10.875981,0.304841,5.188724,1.567496,2.531623
min,1.000000,1.000000,0.000000,0.000000,0.200000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,117.000000,3.000000,0.000000,0.000000,14.300000,0.000000,0.000000,2.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,4.000000,0.000000,2.000000,0.000000,0.000000
50%,303.000000,5.000000,0.000000,0.000000,34.600000,0.000000,0.000000,5.000000,3.000000,1.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,12.000000,0.000000,6.000000,1.000000,1.000000
75%,493.000000,7.000000,0.000000,0.000000,56.400000,4.000000,2.000000,12.000000,7.000000,3.000000,...,1.000000,0.000000,0.000000,2.000000,0.000000,16.500000,0.000000,10.000000,2.000000,2.000000
max,1230.000000,13.000000,15.000000,7.000000,133.000000,36.000000,10.000000,83.000000,35.000000,18.000000,...,3.000000,3.000000,1.000000,13.000000,3.000000,61.000000,1.000000,20.000000,5.000000,12.000000

In [26]:
clean_filled_player_data = clean_player_data.fillna(0)
clean_filled_player_data.describe()

,minutes_played,match_played,goals,assists,distance_covered,corner_taken,offsides,dribbles,tackles,t_won,...,headers,penalties,others,inside_area,outside_areas,saved,saved_penalties,conceded,cleansheets,punches made
count,745.000000,745.000000,745.000000,745.000000,745.000000,745.000000,745.00000,745.000000,745.000000,745.000000,...,745.000000,745.000000,745.000000,745.000000,745.000000,745.000000,745.000000,745.000000,745.000000,745.000000
mean,332.491275,5.100671,0.493960,0.377181,38.268456,0.800000,0.33557,2.159732,4.012081,1.770470,...,0.080537,0.048322,0.005369,0.453691,0.055034,0.993289,0.008054,0.526174,0.103356,0.153020
std,248.123209,2.716796,1.314836,0.846412,27.988625,3.364744,1.24548,6.638920,4.892788,2.511198,...,0.334342,0.284596,0.073126,1.233849,0.276167,4.550636,0.089440,2.306996,0.562064,0.878779
min,1.000000,1.000000,0.000000,0.000000,0.200000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,117.000000,3.000000,0.000000,0.000000,14.300000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,303.000000,5.000000,0.000000,0.000000,34.600000,0.000000,0.00000,0.000000,2.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,493.000000,7.000000,0.000000,0.000000,56.400000,0.000000,0.00000,0.000000,6.000000,3.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1230.000000,13.000000,15.000000,7.000000,133.000000,36.000000,10.00000,83.000000,35.000000,18.000000,...,3.000000,3.000000,1.000000,13.000000,3.000000,61.000000,1.000000,20.000000,5.000000,12.000000

# Add Data

## Convert Data