In [5]:
import pandas as pd

## Read Player Data

In [6]:
player_data = pd.read_csv("player_data_202502101344.csv")
club_data = pd.read_csv('club_ks_att_go_df_dis_atm_gl_dsc_202502060055.csv')

In [13]:
player_data.head()

,player_name,club,position,minutes_played,match_played,goals,assists,distance_covered,corner_taken,offsides,...,headers,penalties,others,inside_area,outside_areas,saved,saved_penalties,conceded,cleansheets,punches made
0,Courtois,Real Madrid,Goalkeeper,1230,13,0,0,64.2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,61.0,1.0,14.0,5.0,4.0
1,Vinícius Júnior,Real Madrid,Forward,1199,13,4,6,133.0,3.0,4.0,...,0.0,0.0,0.0,4.0,0.0,NaN,NaN,NaN,NaN,NaN
2,Benzema,Real Madrid,Forward,1106,12,15,1,121.5,2.0,9.0,...,3.0,3.0,0.0,13.0,2.0,NaN,NaN,NaN,NaN,NaN
3,Modrić,Real Madrid,Midfielder,1077,13,0,4,124.5,10.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Éder Militão,Real Madrid,Defender,1076,12,0,0,110.4,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
player_data.describe()

,minutes_played,match_played,goals,assists,distance_covered,corner_taken,offsides,dribbles,tackles,t_won,...,headers,penalties,others,inside_area,outside_areas,saved,saved_penalties,conceded,cleansheets,punches made
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,328.000000,328.000000,328.000000,887.000000,887.000000,...,319.000000,319.000000,319.000000,319.000000,319.000000,134.000000,134.000000,134.000000,134.000000,134.000000
mean,342.827000,5.203000,0.429000,0.364000,39.560500,2.158537,0.762195,6.341463,5.310034,2.197294,...,0.188088,0.112853,0.012539,1.297806,0.344828,7.276119,0.044776,3.089552,1.164179,0.895522
std,238.900239,2.640599,1.167185,0.822302,27.217944,5.028286,1.789753,8.747521,4.816701,2.444525,...,0.491163,0.426840,0.111449,1.641357,0.532199,8.608784,0.207588,4.750089,1.164603,1.928296
min,1.000000,1.000000,0.000000,0.000000,0.200000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,142.000000,3.000000,0.000000,0.000000,16.675000,0.000000,0.000000,2.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,1.000000,0.000000
50%,326.000000,5.000000,0.000000,0.000000,36.850000,0.000000,0.000000,3.000000,4.000000,1.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,3.000000,0.000000,0.000000,1.000000,0.000000
75%,500.000000,7.000000,0.000000,0.000000,58.550000,1.000000,1.000000,7.000000,9.000000,3.000000,...,0.000000,0.000000,0.000000,2.000000,1.000000,9.000000,0.000000,6.000000,1.000000,1.000000
max,1230.000000,13.000000,15.000000,7.000000,133.000000,36.000000,10.000000,83.000000,35.000000,18.000000,...,3.000000,3.000000,1.000000,13.000000,3.000000,61.000000,1.000000,20.000000,5.000000,12.000000

## Clean Data

In [22]:
duplicates = player_data[player_data.duplicated(subset=["player_name",'club'],keep=False)]
duplicates.describe()

,minutes_played,match_played,goals,assists,distance_covered,corner_taken,offsides,dribbles,tackles,t_won,...,headers,penalties,others,inside_area,outside_areas,saved,saved_penalties,conceded,cleansheets,punches made
count,284.000000,284.000000,284.000000,284.000000,284.000000,156.000000,156.0,156.000000,284.000000,284.000000,...,140.0,140.0,140.0,140.000000,140.000000,84.000000,84.0,84.000000,84.000000,84.000000
mean,369.169014,5.471831,0.239437,0.323944,42.738732,0.820513,0.0,3.333333,6.549296,2.478873,...,0.0,0.0,0.0,0.628571,0.514286,3.238095,0.0,0.523810,1.095238,0.142857
std,209.690432,2.415187,0.503410,0.757057,24.609719,2.434926,0.0,1.793657,4.016886,1.981249,...,0.0,0.0,0.0,0.723131,0.501590,1.313682,0.0,1.571402,0.926440,0.469372
min,18.000000,1.000000,0.000000,0.000000,3.300000,0.000000,0.0,1.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.000000,0.000000,2.000000,0.0,0.000000,0.000000,0.000000
25%,180.000000,4.000000,0.000000,0.000000,21.600000,0.000000,0.0,3.000000,3.000000,1.000000,...,0.0,0.0,0.0,0.000000,0.000000,3.000000,0.0,0.000000,1.000000,0.000000
50%,347.000000,5.500000,0.000000,0.000000,39.300000,0.000000,0.0,3.000000,7.000000,2.000000,...,0.0,0.0,0.0,0.000000,1.000000,3.000000,0.0,0.000000,1.000000,0.000000
75%,540.000000,8.000000,0.000000,0.000000,66.600000,0.000000,0.0,4.000000,10.000000,4.000000,...,0.0,0.0,0.0,1.000000,1.000000,3.000000,0.0,0.000000,1.000000,0.000000
max,867.000000,10.000000,2.000000,4.000000,96.300000,8.000000,0.0,8.000000,14.000000,7.000000,...,0.0,0.0,0.0,2.000000,1.000000,9.000000,0.0,7.000000,5.000000,2.000000

In [20]:
clean_player_data = player_data.drop_duplicates(subset=['player_name', 'club'], keep='first')

In [23]:
clean_player_data.describe()

,minutes_played,match_played,goals,assists,distance_covered,corner_taken,offsides,dribbles,tackles,t_won,...,headers,penalties,others,inside_area,outside_areas,saved,saved_penalties,conceded,cleansheets,punches made
count,745.000000,745.000000,745.000000,745.000000,745.000000,183.000000,183.000000,183.000000,632.000000,632.000000,...,190.000000,190.000000,190.000000,190.000000,190.000000,59.000000,59.000000,59.000000,59.000000,59.000000
mean,332.491275,5.100671,0.493960,0.377181,38.268456,3.256831,1.366120,8.792350,4.729430,2.087025,...,0.315789,0.189474,0.021053,1.778947,0.215789,12.542373,0.101695,6.644068,1.305085,1.932203
std,248.123209,2.716796,1.314836,0.846412,27.988625,6.183516,2.219383,11.024476,4.982812,2.602636,...,0.604448,0.540326,0.143939,1.903375,0.515129,10.875981,0.304841,5.188724,1.567496,2.531623
min,1.000000,1.000000,0.000000,0.000000,0.200000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,117.000000,3.000000,0.000000,0.000000,14.300000,0.000000,0.000000,2.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,4.000000,0.000000,2.000000,0.000000,0.000000
50%,303.000000,5.000000,0.000000,0.000000,34.600000,0.000000,0.000000,5.000000,3.000000,1.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,12.000000,0.000000,6.000000,1.000000,1.000000
75%,493.000000,7.000000,0.000000,0.000000,56.400000,4.000000,2.000000,12.000000,7.000000,3.000000,...,1.000000,0.000000,0.000000,2.000000,0.000000,16.500000,0.000000,10.000000,2.000000,2.000000
max,1230.000000,13.000000,15.000000,7.000000,133.000000,36.000000,10.000000,83.000000,35.000000,18.000000,...,3.000000,3.000000,1.000000,13.000000,3.000000,61.000000,1.000000,20.000000,5.000000,12.000000

In [26]:
clean_filled_player_data = clean_player_data.fillna(0)
clean_filled_player_data.describe()

,minutes_played,match_played,goals,assists,distance_covered,corner_taken,offsides,dribbles,tackles,t_won,...,headers,penalties,others,inside_area,outside_areas,saved,saved_penalties,conceded,cleansheets,punches made
count,745.000000,745.000000,745.000000,745.000000,745.000000,745.000000,745.00000,745.000000,745.000000,745.000000,...,745.000000,745.000000,745.000000,745.000000,745.000000,745.000000,745.000000,745.000000,745.000000,745.000000
mean,332.491275,5.100671,0.493960,0.377181,38.268456,0.800000,0.33557,2.159732,4.012081,1.770470,...,0.080537,0.048322,0.005369,0.453691,0.055034,0.993289,0.008054,0.526174,0.103356,0.153020
std,248.123209,2.716796,1.314836,0.846412,27.988625,3.364744,1.24548,6.638920,4.892788,2.511198,...,0.334342,0.284596,0.073126,1.233849,0.276167,4.550636,0.089440,2.306996,0.562064,0.878779
min,1.000000,1.000000,0.000000,0.000000,0.200000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,117.000000,3.000000,0.000000,0.000000,14.300000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,303.000000,5.000000,0.000000,0.000000,34.600000,0.000000,0.00000,0.000000,2.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,493.000000,7.000000,0.000000,0.000000,56.400000,0.000000,0.00000,0.000000,6.000000,3.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1230.000000,13.000000,15.000000,7.000000,133.000000,36.000000,10.00000,83.000000,35.000000,18.000000,...,3.000000,3.000000,1.000000,13.000000,3.000000,61.000000,1.000000,20.000000,5.000000,12.000000

# Add Data

In [99]:
(player_data["club"].unique())

array(['Real Madrid', 'Liverpool', 'Villarreal', 'Man. City', 'Benfica',
       'Atlético', 'Bayern', 'Chelsea', 'LOSC', 'Inter', 'Salzburg',
       'Ajax', 'Paris', 'Sporting CP', 'Juventus', 'Man. United',
       'Club Brugge', 'Sheriff', 'Wolfsburg', 'Dynamo Kyiv', 'Sevilla',
       'Shakhtar Donetsk', 'Zenit', 'Dortmund', 'Atalanta', 'Porto',
       'Barcelona', 'Young Boys', 'Leipzig', 'Malmö', 'Milan', 'Beşiktaş'],
      dtype=object)

In [100]:
# Champions League stages mapping
champions_league_stages = {
    "Group Stage": ["Leipzig", "Club Brugge", "Porto", "Milan", "Dortmund", "Beşiktaş", "Sheriff", 
                    "Shakhtar Donetsk", "Barcelona", "Dynamo Kyiv", "Atalanta", "Young Boys", 
                    "Sevilla", "Wolfsburg", "Zenit", "Malmö"],
    "Round of 16": ["Ajax", "Inter", "Sporting CP", "Juventus", "Salzburg", "Man. United", "LOSC", "Paris"],
    "Quarter Finals": ["Benfica", "Bayern", "Atlético", "Chelsea"],
    "Semi Finals": ["Villarreal", "Man. City"],
    "Finals": ["Liverpool"],
    "Winner": ["Real Madrid"]
}

In [101]:
# Function to get the Champions League stage of a club
def get_cl_stage(club):
    for stage, clubs in champions_league_stages.items():
        if club in clubs:
            return stage
    return "Not Participated"

In [102]:
# Add the column to player_data
clean_filled_player_data["Champions_League_Stage"] = clean_filled_player_data["club"].apply(get_cl_stage)
club_data["Champions_League_Stage"] = club_data['club'].apply(get_cl_stage)

In [103]:
clean_filled_player_data

,player_name,club,position,minutes_played,match_played,goals,assists,distance_covered,corner_taken,offsides,...,others,inside_area,outside_areas,saved,saved_penalties,conceded,cleansheets,punches made,Champions_League_Stage,Total Points
0,Courtois,Real Madrid,Goalkeeper,1230,13,0,0,64.2,0.0,0.0,...,0.0,0.0,0.0,61.0,1.0,14.0,5.0,4.0,Winner,4510.0
1,Vinícius Júnior,Real Madrid,Forward,1199,13,4,6,133.0,3.0,4.0,...,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,Winner,2349.0
2,Benzema,Real Madrid,Forward,1106,12,15,1,121.5,2.0,9.0,...,0.0,13.0,2.0,0.0,0.0,0.0,0.0,0.0,Winner,2433.0
3,Modrić,Real Madrid,Midfielder,1077,13,0,4,124.5,10.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Winner,4826.0
4,Éder Militão,Real Madrid,Defender,1076,12,0,0,110.4,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Winner,5370.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Miretti,Juventus,Midfielder,1,1,0,0,0.8,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Round of 16,14.0
996,Gil Dias,Benfica,Midfielder,1,1,0,0,0.7,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Quarter Finals,15.0
997,Rodrigo Ribeiro,Sporting CP,Forward,1,1,0,0,0.7,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Round of 16,10.0
998,Cojocari,Sheriff,Defender,1,1,0,0,0.5,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Group Stage,5.0
999,Maouassa,Club Brugge,Defender,1,1,0,0,0.2,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Group Stage,5.0

In [104]:
(club_data.columns)

Index(['club', 'total_minutes_played', 'total_matches', 'total_goals',
       'total_assists', 'average_distance_covered', 'total_corners',
       'total_dribbles', 'total_offsides', 'total_right_foot_goals',
       'total_left_foot_goals', 'total_header_goals', 'total_other_goals',
       'total_penalties', 'total_inside_goals', 'total_outside_goals',
       'total_balls_recovered', 'total_tackles', 'total_tackles_won',
       'total_tackles_lost', 'total_clearance_attempted', 'avg_pass_accuracy',
       'total_pass_attempted', 'total_pass_completed', 'avg_cross_accuracy',
       'total_cross_attempted', 'total_cross_completed',
       'total_freekicks_taken', 'total_attempts', 'total_on_target',
       'total_off_target', 'total_blocked', 'total_saves_attempted',
       'total_saved', 'total_conceded', 'total_saved_penalties',
       'total_cleansheets', 'total_saves_by_punches', 'total_red',
       'total_yellow', 'total_fouls_committed', 'total_fouls_suffered',
       'Champions_League_Stage', 'Total Points'],
      dtype='object')

In [105]:
clean_filled_player_data.columns

Index(['player_name', 'club', 'position', 'minutes_played', 'match_played',
       'goals', 'assists', 'distance_covered', 'corner_taken', 'offsides',
       'dribbles', 'tackles', 't_won', 't_lost', 'balls_recoverd',
       'clearance_attempted', 'total_attempts', 'on_target', 'off_target',
       'blocked', 'red', 'yellow', 'fouls_committed', 'fouls_suffered',
       'cross_accuracy', 'cross_attempted', 'cross_complted',
       'freekicks_taken', 'pass_accuracy', 'pass_attempted', 'pass_completed',
       'right_foot', 'left_foot', 'headers', 'penalties', 'others',
       'inside_area', 'outside_areas', 'saved', 'saved_penalties', 'conceded',
       'cleansheets', 'punches made', 'Champions_League_Stage',
       'Total Points'],
      dtype='object')

In [106]:
# =========================
# Define Position-Based Weights for Every Column
# =========================
position_weights = {
    'Forward': {
        'goals': 10, 'assists': 7, 'dribbles': 4, 'total_attempts': 3, 'on_target': 4,
        'off_target': -2, 'blocked': -1, 'right_foot': 5, 'left_foot': 6,
        'headers': 8, 'others': 5, 'penalties': 7, 'inside_area': 4,
        'outside_areas': 6, 'balls_recoverd': 3, 'tackles': 3, 't_won': 3,
        't_lost': -2, 'clearance_attempted': 2,
        'pass_accuracy': 3, 'pass_attempted': 1, 'pass_completed': 2, 'cross_accuracy': 4,
        'cross_attempted': 1, 'cross_complted': 3, 'freekicks_taken': 4,
        'saved': 0, 'saved_penalties': 0, 'conceded': 0, 'cleansheets': 1, 'punches made': 0,
        'red': -10, 'yellow': -5, 'fouls_committed': -2, 'fouls_suffered': 3
    },
    'Midfielder': {
        'goals': 8, 'assists': 9, 'dribbles': 4, 'total_attempts': 3, 'on_target': 3,
        'off_target': -2, 'blocked': -1, 'right_foot': 4, 'left_foot': 5,
        'headers': 7, 'others': 4, 'penalties': 6, 'inside_area': 3,
        'outside_areas': 5, 'balls_recoverd': 4, 'tackles': 4, 't_won': 4,
        't_lost': -2, 'clearance_attempted': 3,
        'pass_accuracy': 5, 'pass_attempted': 2, 'pass_completed': 3, 'cross_accuracy': 5,
        'cross_attempted': 2, 'cross_complted': 4, 'freekicks_taken': 3,
        'saved': 0, 'saved_penalties': 0, 'conceded': 0, 'cleansheets': 2, 'punches made': 0,
        'red': -10, 'yellow': -5, 'fouls_committed': -2, 'fouls_suffered': 3
    },
    'Defender': {
        'goals': 6, 'assists': 6, 'dribbles': 2, 'total_attempts': 2, 'on_target': 2,
        'off_target': -2, 'blocked': -1, 'right_foot': 3, 'left_foot': 4,
        'headers': 6, 'others': 3, 'penalties': 5, 'inside_area': 2,
        'outside_areas': 4, 'balls_recoverd': 6, 'tackles': 6, 't_won': 6,
        't_lost': -2, 'clearance_attempted': 7,
        'pass_accuracy': 4, 'pass_attempted': 3, 'pass_completed': 4, 'cross_accuracy': 3,
        'cross_attempted': 2, 'cross_complted': 3, 'freekicks_taken': 2,
        'saved': 1, 'saved_penalties': 2, 'conceded': -3, 'cleansheets': 8, 'punches made': 1,
        'red': -12, 'yellow': -6, 'fouls_committed': -3, 'fouls_suffered': 2
    },
    'Goalkeeper': {
        'goals': 5, 'assists': 5, 'dribbles': 1, 'total_attempts': 0, 'on_target': 1,
        'off_target': -2, 'blocked': -1, 'right_foot': 2, 'left_foot': 3,
        'headers': 4, 'others': 2, 'penalties': 4, 'inside_area': 1,
        'outside_areas': 3, 'balls_recoverd': 2, 'tackles': 2, 't_won': 2,
        't_lost': -2, 'clearance_attempted': 1,
        'pass_accuracy': 4, 'pass_attempted': 4, 'pass_completed': 5, 'cross_accuracy': 2,
        'cross_attempted': 1, 'cross_complted': 2, 'freekicks_taken': 1,
        'saved': 6, 'saved_penalties': 10, 'conceded': -5, 'cleansheets': 10, 'punches made': 4,
        'red': -15, 'yellow': -7, 'fouls_committed': -3, 'fouls_suffered': 1
    }
}

# =========================
# Define Weights for Club-Level Metrics
# =========================

club_weights = {
    'total_goals': 10, 'total_assists': 7,
    'average_distance_covered': 2, 'total_corners': 3, 'total_offsides': -3, 'total_dribbles': 4,
    'total_right_foot_goals': 5, 'total_left_foot_goals': 6, 'total_header_goals': 8, 
    'total_other_goals': 5, 'total_penalties': 7, 'total_inside_goals': 4, 'total_outside_goals': 6,
    'total_balls_recovered': 4, 'total_tackles': 6, 'total_tackles_won': 6, 'total_tackles_lost': -2, 
    'total_clearance_attempted': 7, 'avg_pass_accuracy': 4, 'total_pass_attempted': 2, 
    'total_pass_completed': 3, 'avg_cross_accuracy': 5, 'total_cross_attempted': 2, 
    'total_cross_completed': 4, 'total_freekicks_taken': 3, 'total_attempts': 3, 'total_on_target': 4,
    'total_off_target': -2, 'total_blocked': -1, 'total_saves_attempted': 6, 'total_saved': 8,
    'total_conceded': -3, 'total_saved_penalties': 10, 'total_cleansheets': 10, 
    'total_saves_by_punches': 4, 'total_red': -12, 'total_yellow': -6, 
    'total_fouls_committed': -2, 'total_fouls_suffered': 3
}

# =========================
# Champions League Bonus
# =========================
cl_stage_points = {'Group Stage': 5, 'Round of 16': 10, 'Quarter Finals': 15, 'Semi Finals': 20, 'Finals': 30, 'Winner': 50}

In [107]:
# =========================
# Function to Calculate Player Points
# =========================

def calculate_player_points(row):
    position = row['position']
    if position in position_weights:
        total_points = sum(
            row.get(metric, 0) * weight for metric, weight in position_weights[position].items()
        )
        total_points += cl_stage_points.get(row['Champions_League_Stage'], 0)
        return total_points
    return 0

# =========================
# Function to Calculate Club Points
# =========================
def calculate_club_points(row):
    total_points = sum(
        row.get(metric, 0) * weight for metric, weight in club_weights.items()
    )
    total_points += cl_stage_points.get(row['Champions_League_Stage'], 0)
    return total_points

In [108]:
clean_filled_player_data['Total Points'] = clean_filled_player_data.apply(calculate_player_points, axis=1)
club_data['Total Points'] = club_data.apply(calculate_club_points, axis=1)

In [109]:
clean_filled_player_data.head()

,player_name,club,position,minutes_played,match_played,goals,assists,distance_covered,corner_taken,offsides,...,others,inside_area,outside_areas,saved,saved_penalties,conceded,cleansheets,punches made,Champions_League_Stage,Total Points
0,Courtois,Real Madrid,Goalkeeper,1230,13,0,0,64.2,0.0,0.0,...,0.0,0.0,0.0,61.0,1.0,14.0,5.0,4.0,Winner,4510.0
1,Vinícius Júnior,Real Madrid,Forward,1199,13,4,6,133.0,3.0,4.0,...,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,Winner,2349.0
2,Benzema,Real Madrid,Forward,1106,12,15,1,121.5,2.0,9.0,...,0.0,13.0,2.0,0.0,0.0,0.0,0.0,0.0,Winner,2433.0
3,Modrić,Real Madrid,Midfielder,1077,13,0,4,124.5,10.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Winner,4826.0
4,Éder Militão,Real Madrid,Defender,1076,12,0,0,110.4,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Winner,5370.0

In [110]:
club_data.head()

,club,total_minutes_played,total_matches,total_goals,total_assists,average_distance_covered,total_corners,total_dribbles,total_offsides,total_right_foot_goals,...,total_conceded,total_saved_penalties,total_cleansheets,total_saves_by_punches,total_red,total_yellow,total_fouls_committed,total_fouls_suffered,Champions_League_Stage,Total Points
0,Ajax,720,8,21,17,46.44,38,96,16,5,...,8,0,2,2,15,0,117,75,Round of 16,26464.92
1,Atalanta,540,6,12,11,33.73,10,57,11,4,...,13,0,1,1,9,0,68,73,Group Stage,17677.61
2,Atlético,900,10,9,7,52.09,15,47,9,3,...,10,0,3,2,25,4,139,123,Quarter Finals,21670.32
3,Barcelona,540,6,2,1,30.53,0,0,1,2,...,9,0,3,2,13,1,83,65,Group Stage,19643.68
4,Bayern,876,10,30,24,49.42,20,145,25,13,...,7,0,4,3,12,0,115,94,Quarter Finals,35531.31

# Test Data

In [111]:
club_data[club_data["Champions_League_Stage"] == "Not Participated"]

,club,total_minutes_played,total_matches,total_goals,total_assists,average_distance_covered,total_corners,total_dribbles,total_offsides,total_right_foot_goals,...,total_conceded,total_saved_penalties,total_cleansheets,total_saves_by_punches,total_red,total_yellow,total_fouls_committed,total_fouls_suffered,Champions_League_Stage,Total Points
28,Total,21851,254,368,281,38.27,588,1581,250,178,...,380,6,70,110,492,25,2897,2643,Not Participated,693560.14

In [112]:
clean_filled_player_data[clean_filled_player_data["Champions_League_Stage"] == "Not Participated"]

Empty DataFrame
Columns: [player_name, club, position, minutes_played, match_played, goals, assists, distance_covered, corner_taken, offsides, dribbles, tackles, t_won, t_lost, balls_recoverd, clearance_attempted, total_attempts, on_target, off_target, blocked, red, yellow, fouls_committed, fouls_suffered, cross_accuracy, cross_attempted, cross_complted, freekicks_taken, pass_accuracy, pass_attempted, pass_completed, right_foot, left_foot, headers, penalties, others, inside_area, outside_areas, saved, saved_penalties, conceded, cleansheets, punches made, Champions_League_Stage, Total Points]
Index: []

[0 rows x 45 columns]

## Convert Data

In [113]:
clean_filled_player_data.to_excel("Complete Player Data UCL 21-22.xlsx")
club_data.to_excel("Complete Club Data UCL 21-22.xlsx")